import UserPic from "../../../../images/avatar/b-sm.jpg";

export const recentOrderData = [
  {
    order: "#95954",
    img: null,
    initial: "EM",
    theme: "purple-dim",
    name: "EL AMRI Mohammed",
    date: "Now",
    ref: "SUB-2309232",
    status: "Available",
  },
  {
    order: "#95850",
    img: null,
    initial: "OI",
    theme: "primary-dim",
    name: "OUAIREM Imad",
    date: "3 minutes ago",
    ref: "SUB-2309154",
    amount: "596.75",
    status: "Offline",
  },
  {
    order: "#95810",
    img: UserPic,
    initial: "DE",
    theme: "danger-dim",
    name: "KARIMI Youssef",
    date: "Now",
    ref: "SUB-2309143",
    status: "Available",
  },
  {
    order: "#95810",
    img: null,
    initial: "TA",
    theme: "purple-dim",
    name: "TOULON Anass",
    date: "Now",
    ref: "SUB-2305984",
    status: "Available",
  },
  {
    order: "#95135",
    img: null,
    initial: "OI",
    theme: "success-dim",
    name: "OUHTI Imane",
    date: "1 minute ago",
    ref: "SUB-2305564",
    amount: "1099.99",
    status: "Away",
  },
];
